### ISSUE TITLE
[BUG]Unhandled exception in [StandaloneCoroutine{Cancelling}@18859641, EdtCoroutineDispatcher@28d37be1]

### ISSUE THREAD

**Issue by TomGardner** [flikas/archived-idea-spring-boot-assistant#26] opened 2022-06-24 18:17 UTC
## What happened
> Please describe what you were doing when this exception occurred.

## Expected behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

## Version information
- OS: `Linux 5.13.0-51-generic amd64`
- IDE: `IntelliJ IDEA 2021.3.3(IU-213.7172.25)`
- Plugin: `Spring Boot Assistant 0.14.3`

## Exception
Unhandled exception in [StandaloneCoroutine{Cancelling}@18859641, EdtCoroutineDispatcher@28d37be1]

<details><summary>Stack trace</summary>

```
java.lang.IllegalAccessError: Should never be called
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.getDocumentationForValue(MetadataNonPropertySuggestionNode.java:416)
	at in.oneton.idea.spring.assistant.plugin.suggestion.completion.YamlDocumentationProvider$DocumentationProxyElement.generateDoc(YamlDocumentationProvider.java:189)
	at in.oneton.idea.spring.assistant.plugin.suggestion.completion.YamlDocumentationProvider.generateDoc(YamlDocumentationProvider.java:39)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:141)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:73)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:58)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt:25)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:65)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:12)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$3.run(ReadAction.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.application.rw.ReadAction.tryReadAction(ReadAction.kt:71)
	at com.intellij.openapi.application.rw.ReadAction.access$tryReadAction(ReadAction.kt:14)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2$2.run(ReadAction.kt:62)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

## Additional context
> Add any other context about the problem here.

**Comment by flikas** [comment] 2022-11-16 12:41
Duplicate of #25

**Closed as completed by flikas** 2022-11-16 12:41 UTC
Labels: duplicate
