### ISSUE TITLE
[BUG]A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

### ISSUE THREAD

**Issue by kurzawsl** [flikas/archived-idea-spring-boot-assistant#44] opened 2022-11-03 09:08 UTC
## What happened
> Please describe what you were doing when this exception occurred.

## Expected behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

## Version information
- OS: `Mac OS X 12.6 x86_64`
- IDE: `IntelliJ IDEA 2022.1(IU-221.5080.210)`
- Plugin: `Spring Boot Assistant 0.14.0`

## Exception
A suspiciously high nesting of suppressPrioritizing, forgot to call restorePrioritizing?

<details><summary>Stack trace</summary>

```
java.lang.Throwable
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:127)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.suppressPrioritizing(CoreProgressManager.java:843)
	at com.intellij.openapi.progress.impl.CoreProgressManager.avoidBlockingPrioritizingThread(CoreProgressManager.java:905)
	at com.intellij.openapi.progress.impl.CoreProgressManager.checkLowPriorityReallyApplicable(CoreProgressManager.java:885)
	at com.intellij.openapi.progress.impl.CoreProgressManager.sleepIfNeededToGivePriorityToAnotherThread(CoreProgressManager.java:861)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$new$0(ProgressManagerImpl.java:28)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runCheckCanceledHooks(CoreProgressManager.java:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:148)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:211)
	at com.intellij.openapi.progress.ProgressIndicatorProvider.checkCanceled(ProgressIndicatorProvider.java:23)
	at com.intellij.psi.impl.source.tree.CompositeElement.getPsi(CompositeElement.java:687)
	at com.intellij.psi.impl.source.SourceTreeToPsiMap.treeElementToPsi(SourceTreeToPsiMap.java:16)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeElementFromText(PsiJavaParserFacadeImpl.java:229)
	at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createTypeInner(PsiJavaParserFacadeImpl.java:240)
	at com.intellij.psi.impl.PsiElementFactoryImpl.createTypeFromText(PsiElementFactoryImpl.java:670)
	at in.oneton.idea.spring.assistant.plugin.misc.PsiCustomUtil.safeGetValidType(PsiCustomUtil.java:91)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.updateGroupType(MetadataNonPropertySuggestionNode.java:545)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.setGroup(MetadataNonPropertySuggestionNode.java:445)
	at in.oneton.idea.spring.assistant.plugin.suggestion.metadata.MetadataNonPropertySuggestionNode.addChildren(MetadataNonPropertySuggestionNode.java:236)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.addGroupsToIndex(SuggestionServiceImpl.java:434)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.buildMetadataHierarchy(SuggestionServiceImpl.java:382)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.processContainers(SuggestionServiceImpl.java:351)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$11(SuggestionServiceImpl.java:269)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:150)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$12(SuggestionServiceImpl.java:259)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

## Additional context
> Add any other context about the problem here.

**Comment by flikas** [comment] 2022-12-04 09:32
Duplicate of #34

**Closed as completed by flikas** 2022-12-04 09:32 UTC
