### ISSUE TITLE
[BUG]Java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =jrt://C:/Users/salva/.jdks/openjdk-15.0.1!/java.naming (class java.lang.String), hashCode=152569537; object #2 =jrt://C:/Users/salva/.jdks/openjdk-15.0.1!/java.naming (class java.lang.String), hashCode=152569537

### ISSUE THREAD

**Issue by SalvatoreCataniaVS** [flikas/archived-idea-spring-boot-assistant#53] opened 2022-12-05 11:25 UTC
## What happened
> Please describe what you were doing when this exception occurred.

## Expected behavior
> A clear and concise description of what you expected to happen.

## Screenshots
> If applicable, add screenshots to help explain your problem.

## Version information
- OS: `Windows 10 10.0 amd64`
- IDE: `IntelliJ IDEA 2022.3(IC-223.7571.182)`
- Plugin: `Spring Boot Assistant 0.17.1`

## Exception
null

<details><summary>Stack trace</summary>

```
java.lang.IllegalArgumentException: Equal objects must have equal hashcodes. During rehashing, Trove discovered that the following two objects claim to be equal (as in java.lang.Object.equals() or TObjectHashingStrategy.equals()) but their hashCodes (or those calculated by your TObjectHashingStrategy) are not equal.This violates the general contract of java.lang.Object.hashCode().  See bullet point two in that method's documentation. object #1 =jrt://C:/Users/salva/.jdks/openjdk-15.0.1!/java.naming (class java.lang.String), hashCode=152569537; object #2 =jrt://C:/Users/salva/.jdks/openjdk-15.0.1!/java.naming (class java.lang.String), hashCode=152569537
	at gnu.trove.TObjectHash.throwObjectContractViolation(TObjectHash.java:343)
	at gnu.trove.THashMap.rehash(THashMap.java:303)
	at gnu.trove.THash.postInsertHook(THash.java:292)
	at gnu.trove.THashMap.put(THashMap.java:167)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.computeNewContainersToProcess(SuggestionServiceImpl.java:307)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$11(SuggestionServiceImpl.java:267)
	at com.intellij.openapi.project.DumbService.lambda$runReadActionInSmartMode$1(DumbService.java:156)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:873)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.java:149)
	at in.oneton.idea.spring.assistant.plugin.suggestion.service.SuggestionServiceImpl.lambda$reindex$12(SuggestionServiceImpl.java:260)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

## Additional context
> Add any other context about the problem here.

**Comment by flikas** [comment] 2022-12-10 15:55
Duplicate of #58

**Closed as completed by flikas** 2022-12-10 15:55 UTC
