### ISSUE TITLE
spring boot assistant is not seen in Generators of Intellij

### ISSUE THREAD

**Issue by vikramg85** [flikas/archived-idea-spring-boot-assistant#49] opened 2022-11-24 13:15 UTC
## What happened
When spring boot assistant is installed and enabled in Intellij community version mentioned below. It does not show in the list of new project Generators list. I restarted Intellij, still it is not updated in list.

## To Reproduce
1. Go to 'Files'
2. Click on 'New Project'
3. Scroll down to 'Generators'
4. Spring assistant is not seen in the list
![springBootAssistantNotInList](https://user-images.githubusercontent.com/16681114/203793357-45d188db-6f60-4789-8c70-8b05e1857591.PNG)

## Version information
IntelliJ IDEA 2022.2.4 (Community Edition)
Build #IC-222.4459.24, built on November 22, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

Spring Boot Assistant 0.17.0

## Exception
Copy and paste all the stack traces from IDE.

**Comment by flikas** [comment] 2022-12-04 06:50
Duplicate of #45

**Closed as completed by flikas** 2022-12-04 06:50 UTC
Labels: duplicate, enhancement
